name: Build Wheels

on:
  workflow_dispatch
  # push:
  #   branches: [ master ]

env:
  PYTHONUTF8: 1

jobs:
  build:
    name: Wheel for python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-13', 'macos-14', 'windows-latest']
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --output-dir dist

      - name: List built wheels
        run: ls dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ocp-tessellate-orion-${{ matrix.os }}-cp${{ matrix.python-version }}
          path: dist/*.whl
