name: Build Wheels

on:
  workflow_dispatch
  # push:
  #   branches: [ master ]

env:
  PYTHONUTF8: 1

jobs:
  build:
    name: Wheel for python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'macos-14' ]  # macos-arm64 only
        python-version: ['3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build wheels
        run: |
          python setup.py bdist_wheel

      - name: List built wheels
        run: ls dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ocp-tessellate-orion-${{ matrix.os }}-cp${{ matrix.python-version }}
          path: dist/*.whl
