name: Releases

on:
  push:
    tags: [ '*' ]

jobs:

  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:

      # see https://github.com/marketplace/actions/download-workflow-artifact
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_wheels.yml
          path: wheels

      - name: List wheels
        run: |
          mkdir dist
          mv wheels/**/*.whl dist
          rm -rf wheels
          ls dist

      # see https://github.com/marketplace/actions/create-release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}
